Fixed indentation.

diff --git a/scripts/runall b/scripts/runall
--- a/scripts/runall
+++ b/scripts/runall
@@ -41,6 +41,7 @@ if [[ $# -gt 0 ]]; then
 	while [[ $# -gt 0 ]]
 	do
 		run "$1"
+		[[ $? -gt 0 ]] && echo "Error" && exit 1
 		shift
 	done
 else
